version: "3"

services:
  postgres:
    image: bitnami/postgresql
    environment:
      - POSTGRES_DATABASE=ecommerce
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
